deploy-odoo:
	@docker run --name odoo -p 8069:8069 -e HOST=odoo-db -e USER=odoo -e PASSWORD=odoo --link odoo-db:odoo-db \
	-v ${PWD}:/mnt/extra-addons -d odoo:10.0

deploy-db:
	@docker run --name odoo-db -p 5432:5432 -e POSTGRES_PASSWORD=odoo -e POSTGRES_USER=odoo \
	-d postgres:9.6

undeploy-db:
	@docker kill odoo-db
	@docker rm odoo-db

undeploy-odoo:
	@docker kill odoo
	@docker rm odoo